name: Build V4L2 Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y git make bc bison openssl curl zip kmod cpio flex libelf-dev libssl-dev libtfm-dev wget device-tree-compiler ca-certificates python3 python-is-python3 binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi

    - name: Prepare clang toolchain
      run: |
        if sudo apt-get install -y clang-21 lld-21 llvm-21 >/dev/null 2>&1; then
          echo "Using system clang-21"
        else
          echo "clang-21 not available on runner, falling back to clang-r547379"
          git clone --depth=1 https://gitlab.com/itsshashanksp/android_prebuilts_clang_host_linux-x86_clang-r547379.git $HOME/clang
          echo "$HOME/clang/bin" >> $GITHUB_PATH
        fi

    - name: Build kernel
      run: |
        chmod +x ./build_kernel.sh
        ./build_kernel.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel-zip
        path: zip/SLEEPY_KERNEL-OSS-test-SWEET-signed.zip
